Время разбивать камни
htmlacademy-ecmascript/2073335-cinemaddict-18 pull request #3
Opened 2022-08-11 12:48 UTC by Domish4

2022-08-11 16:15 UTC, AlexMasterov requested changes

2022-08-11 16:15 UTC, AlexMasterov commented on src/view/footer-view.js
> +const createFooterTemplate = () => (`
https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/f76fe8c32047becdaee8e6ffa0e09af8fce1692c/src/view/footer-view.js#L3

1. В демо проекте скобки `()` для группировки выражений здесь используется только для форматирования разметки. В таком случае их использование теряет смысл.

3. Шаблонные строки сохраняют [_тот самый_](https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/pull/2#discussion_r942258784) перенос строки. Если на основе такой разметки создать элемент, то первым дочерним узлом будет _пустой_ узел типа `#text`, что вообще не требуется и может создать проблемы с рендерингом таких элементов.

https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/f76fe8c32047becdaee8e6ffa0e09af8fce1692c/src/view/footer-view.js#L3-L7

3. У разметки отсутствует родительский узел. Оба узла `<section>` находятся на одном уровне.

<details>
<summary>Покажи пример, как нужно</summary>

```js
const createFooterTemplate = () => (
  `<section class="footer__statistics">
    <p>130 291 movies inside</p>
  </section>`
);
```
</details>

**Нужно похожим образом исправить остальные шаблоны.**

2022-08-11 16:15 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/184180082-273df9cf-93ed-4130-a352-91cf567d4d4b.png)

</details>

<details>
<summary>Ожидание (markup/list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/184180197-aaf49277-dfe8-4a58-b9c4-720ce0d62c2a.png)

</details>


> Доп. списки `films-list films-list--extra` можно отложить

2022-08-11 16:15 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/184180400-edbdabec-088b-4eec-b4a4-f4852a0e4425.png)

</details>

2022-08-11 16:18 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    for (let i = 0; i < 5; i++) {
for (let i = 0; i < `5`; i++) {

Ограничение на показ фильмов есть в ТЗ, как постоянное значение. Поэтому "константа" потребуется.

[`Б 5`](https://up.htmlacademy.ru/ecmascript/18/criteries#b5)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-08-12 08:59 UTC, Domish4 commented on src/presenter/board-presenter.js
> +      render(new FilmCardsView(), this.movieListComponent.getElement());
Я отрисовала все картинки фильмов, они теперь разные, красивые. В итоге т.к их все равно пять, я убрала пока цикл вообще. Так же можно?

2022-08-12 09:00 UTC, Domish4 commented on src/view/footer-view.js
> +const createFooterTemplate = () => (`
Правильно ли я исправила в новом коммите? а то возникли сомнения, может я не так поняла...

2022-08-12 10:51 UTC, AlexMasterov requested changes

2022-08-12 10:51 UTC, AlexMasterov commented on src/view/movie-list-view.js
> +const createMovieListView = () => (
```diff
- const createMovieListView = () => (
+ const createMovieListViewTemplate = () => (
```
Б10

> Функции для создания шаблона `view` в других модулях именуются по-разному, не единообразно

<details>
<summary>Покажи, что еще можно сделать</summary>

В случае нахождения функции создания шаблона внутри модуля (особенно, если она одна), то название можно упростить:

```diff
- const createMovieListView = () => (
+ const createViewTemplate = () => (
```
</details>

2022-08-12 10:51 UTC, AlexMasterov commented on src/view/load-more-button-view.js
> +export default class LoadMoreButtonView {
const create`Load`MoreButtonView = () => '\<button class="films-list__`show`-more">`Show` more\</button>';
export default class `Load`MoreButtonView {

😃

2022-08-12 10:51 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    this.contentContainer = contentContainer;
this.`content`Container = `content`Container;

Перегруз. Вполне достаточно:

```diff
- this.contentContainer = contentContainer;
+ this.container = container;
```

Если используешь суффикс `Element`, то следует назвать так:

```diff
- this.contentContainer = contentContainer;
+ this.containerElement = containerElement;
```

2022-08-12 10:51 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +      render(new FilmCardsView(), this.movieListComponent.getElement());
> Так же можно?

Таким образом ты сделаешь шаблоны и компоненты непригодными для дальнейшего использования.

Проблема не в цикле, а в преждевременном добавление элемента списка в DOM, которое включает его в процесс рендера страницы браузером.

<details>
<summary>Было</summary>

https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/f76fe8c32047becdaee8e6ffa0e09af8fce1692c/src/presenter/board-presenter.js#L13-L23
</details>

<details>
<summary>Ожидалось</summary>

https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/f76fe8c32047becdaee8e6ffa0e09af8fce1692c/src/presenter/board-presenter.js#L16

Здесь элемент рендерится сам в себя. Следовало удалить.

```js
init = (contentContainer) => {
  this.contentContainer = contentContainer; // <- элемент, который уже добавлен DOM и там видим

  for (let i = 0; i < 5; i++) {
    render(new FilmCardsView(), this.movieListComponent.getElement());
  }

  render(this.movieListComponent, this.movieWrapperComponent.getElement());
  render(new LoadMoreButtonView(), this.movieListComponent.getElement());
  render(this.movieWrapperComponent, this.contentComponent.getElement()); // <- завершенный элемент списка рендерится в DOM
};
```
</details>

Нужно доработать с учетом примера.

2022-08-12 10:51 UTC, AlexMasterov commented on src/view/footer-view.js
> +const createFooterTemplate = () => (`
См. пункт 3:
> У разметки отсутствует родительский узел. Оба узла `<section>` находятся на одном уровне

<details>
<summary>view/movie-cards-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/8b5b1d9317daadd48ca23f5daefb4f746e0ce0aa/src/view/movie-cards-view.js#L3-L103
</details>

Шаблон создает повторяющеюся разметку и при этом она не имеет родительского узла.

<details>
<summary>view/movie-list-view.js</summary>

https://github.com/htmlacademy-ecmascript/2073335-cinemaddict-18/blob/8b5b1d9317daadd48ca23f5daefb4f746e0ce0aa/src/view/movie-list-view.js#L3-L105
</details>

Разметка для `movie-list-view` дублируется внутри шаблона и повторяет `movie-cards-view`.js.

2022-08-12 10:55 UTC, AlexMasterov commented on src/presenter/board-presenter.js
> +    this.contentContainer = contentContainer;
Не исправлено.

Критерий `Б6` оставляем на усмотрение случайного проверяющего.

2022-08-12 11:59 UTC, AlexMasterov commented
👍🏻

2022-08-12 12:00 UTC, merged